"""
Tests for _imagedetect: image enumeration, marker detection, marker generation.

Scope (pinned by these tests):
- list_images: returns ImageInfo for every entry under word/media/ that is
  a recognized image format; non-image files in word/media/ are skipped;
  files outside word/media/ are ignored.
- is_marker_image: returns True for PNGs generated by make_marker_png,
  False for any other input (including unrelated PNGs and non-PNG data).
- make_marker_png: produces a valid PNG of the requested size whose bytes
  contain the docxwatermarker marker string in the early portion of the file.

ImageInfo is frozen, immutable, and reports width=0/height=0 if Pillow
cannot decode the image (rather than raising).
"""

from __future__ import annotations

import io
import sys
import zipfile
from pathlib import Path

import pytest
from PIL import Image

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from docxwatermarker._zipops import ZipEntry, read_zip_entries
from docxwatermarker._imagedetect import (
    ImageInfo,
    list_images,
    is_marker_image,
    make_marker_png,
    MARKER_TAG,
)


# ──────────────────────────────────────────────────────────────────────────────
# Helpers to build test fixtures
# ──────────────────────────────────────────────────────────────────────────────

def make_png(width: int, height: int, color=(255, 0, 0, 0)) -> bytes:
    """Build a real PNG of the given size with Pillow."""
    img = Image.new("RGBA", (width, height), color)
    buf = io.BytesIO()
    img.save(buf, "PNG")
    return buf.getvalue()


def make_jpeg(width: int, height: int) -> bytes:
    """Build a real JPEG of the given size with Pillow."""
    img = Image.new("RGB", (width, height), (0, 128, 255))
    buf = io.BytesIO()
    img.save(buf, "JPEG")
    return buf.getvalue()


def make_gif(width: int, height: int) -> bytes:
    """Build a real GIF of the given size with Pillow."""
    img = Image.new("P", (width, height), 1)
    buf = io.BytesIO()
    img.save(buf, "GIF")
    return buf.getvalue()


def build_zip_with(files: dict[str, bytes]) -> dict[str, ZipEntry]:
    """Build an in-memory zip with the given files and return its entries."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for name, data in files.items():
            zf.writestr(name, data)
    return read_zip_entries(buf.getvalue())


# ──────────────────────────────────────────────────────────────────────────────
# list_images
# ──────────────────────────────────────────────────────────────────────────────

class TestListImages:

    def test_finds_png_in_word_media(self):
        png = make_png(100, 80)
        entries = build_zip_with({
            "word/document.xml": b"<doc/>",
            "word/media/image1.png": png,
        })
        images = list_images(entries)
        assert len(images) == 1
        info = images[0]
        assert info.path == "word/media/image1.png"
        assert info.format == "png"
        assert info.width == 100
        assert info.height == 80
        assert info.size_bytes == len(png)

    def test_finds_multiple_images_of_different_formats(self):
        entries = build_zip_with({
            "word/document.xml": b"<doc/>",
            "word/media/image1.png": make_png(50, 50),
            "word/media/image2.jpeg": make_jpeg(200, 100),
            "word/media/image3.gif": make_gif(64, 64),
        })
        images = list_images(entries)
        paths = {img.path for img in images}
        formats = {img.format for img in images}
        assert paths == {
            "word/media/image1.png",
            "word/media/image2.jpeg",
            "word/media/image3.gif",
        }
        assert formats == {"png", "jpeg", "gif"}

    def test_ignores_files_outside_word_media(self):
        """Decision 1: only word/media/ is scanned. Other dirs are ignored,
        even if they contain valid image bytes."""
        png = make_png(10, 10)
        entries = build_zip_with({
            "word/document.xml": b"<doc/>",
            "word/embeddings/image1.png": png,   # outside media/, ignored
            "ppt/media/image1.png": png,         # not word/media/, ignored
            "media/image1.png": png,             # not word/media/, ignored
        })
        assert list_images(entries) == []

    def test_ignores_non_image_files_in_word_media(self):
        """A stray non-image file in word/media/ doesn't trip the detector."""
        entries = build_zip_with({
            "word/media/image1.png": make_png(10, 10),
            "word/media/notes.txt": b"some text, not an image",
        })
        images = list_images(entries)
        assert len(images) == 1
        assert images[0].path == "word/media/image1.png"

    def test_returns_empty_when_no_media(self):
        entries = build_zip_with({
            "word/document.xml": b"<doc/>",
        })
        assert list_images(entries) == []

    def test_unreadable_image_returns_zero_dimensions(self):
        """A corrupted file with a PNG signature but invalid content must
        not crash list_images. It returns width=0, height=0."""
        broken_png = b"\x89PNG\r\n\x1a\n" + b"\x00" * 20  # signature but garbage
        entries = build_zip_with({
            "word/media/broken.png": broken_png,
        })
        images = list_images(entries)
        assert len(images) == 1
        assert images[0].width == 0
        assert images[0].height == 0
        assert images[0].format == "png"  # still detected by signature

    def test_format_is_lowercase(self):
        entries = build_zip_with({
            "word/media/x.png": make_png(5, 5),
            "word/media/y.JPEG": make_jpeg(5, 5),
        })
        images = list_images(entries)
        for img in images:
            assert img.format == img.format.lower()


class TestImageInfo:

    def test_is_frozen(self):
        info = ImageInfo(
            path="word/media/x.png", format="png",
            width=10, height=10, size_bytes=100,
        )
        with pytest.raises(Exception):  # FrozenInstanceError
            info.width = 999  # type: ignore[misc]

    def test_equality_by_value(self):
        a = ImageInfo("p", "png", 1, 2, 3)
        b = ImageInfo("p", "png", 1, 2, 3)
        c = ImageInfo("p", "png", 1, 2, 4)
        assert a == b
        assert a != c


# ──────────────────────────────────────────────────────────────────────────────
# make_marker_png + is_marker_image
# ──────────────────────────────────────────────────────────────────────────────

class TestMakerAndDetection:

    def test_make_marker_produces_valid_png(self):
        data = make_marker_png(size=400)
        # Valid PNG signature
        assert data[:8] == b"\x89PNG\r\n\x1a\n"
        # Pillow can decode it
        img = Image.open(io.BytesIO(data))
        assert img.format == "PNG"
        assert img.size == (400, 400)

    def test_make_marker_default_size_is_square(self):
        data = make_marker_png()  # default size
        img = Image.open(io.BytesIO(data))
        w, h = img.size
        assert w == h
        assert w > 0

    def test_make_marker_size_respected(self):
        for size in (100, 800, 1600):
            data = make_marker_png(size=size)
            img = Image.open(io.BytesIO(data))
            assert img.size == (size, size)

    def test_make_marker_embeds_marker_tag(self):
        """Decision 3 (variant C): the marker is detectable by finding
        MARKER_TAG in the early bytes of the PNG."""
        data = make_marker_png(size=200)
        # The tag must appear in the file head (we look in first ~512 bytes
        # to keep detection cheap).
        assert MARKER_TAG.encode("ascii") in data[:512]

    def test_is_marker_image_true_for_generated(self):
        data = make_marker_png(size=300)
        assert is_marker_image(data) is True

    def test_is_marker_image_false_for_plain_png(self):
        data = make_png(300, 300)  # no marker chunk
        assert is_marker_image(data) is False

    def test_is_marker_image_false_for_jpeg(self):
        data = make_jpeg(300, 300)
        assert is_marker_image(data) is False

    def test_is_marker_image_false_for_garbage(self):
        assert is_marker_image(b"not an image at all") is False
        assert is_marker_image(b"") is False

    def test_is_marker_image_false_for_truncated_png_with_no_marker(self):
        """A short PNG header without the marker text must return False
        cleanly (not crash)."""
        truncated = b"\x89PNG\r\n\x1a\n" + b"\x00" * 16
        assert is_marker_image(truncated) is False


# ──────────────────────────────────────────────────────────────────────────────
# Integration: marker detection on entries from a zip
# ──────────────────────────────────────────────────────────────────────────────

class TestMarkerInZipFlow:

    def test_marker_image_in_zip_is_detected(self):
        """End-to-end: put a marker PNG in word/media/, list images,
        identify the marker."""
        marker = make_marker_png(size=1600)
        plain = make_png(800, 800)
        entries = build_zip_with({
            "word/document.xml": b"<doc/>",
            "word/media/image1.png": marker,
            "word/media/image2.png": plain,
        })
        images = list_images(entries)
        # Find the marker by checking the raw bytes
        marker_paths = [
            img.path for img in images
            if is_marker_image(entries[img.path].data)
        ]
        assert marker_paths == ["word/media/image1.png"]


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v"]))
